- pipeline.groovy
Example: https://ci2.dawg.eu/blue/organizations/jenkins/dlang-test-organization%2Fdmd/detail/PR-1/32/pipeline/28
Not very elegant but I don't think base branch info can be retrieved via Jenkins own metadata
> Support non-master PR base branch

- pipeline.groovy
This goes somewhat against our idea to cache the checkouts.
It seems the impedance mismatch originates from us wanting to run the same testsuite for multiple repositories.
> Github Organization/Branch Sources plugin creates unique workspaces per job (PR/branch)

- pipeline.groovy
- redundant with auto-tester
- take half of the test time
- should run concurrently to project tests (maybe on a separate node)
> drop compiler tests

- pipeline.groovy
After D-YAML broke now twice this month due to regressions:
- https://github.com/dlang-community/D-YAML/issues/66
- https://github.com/dlang-community/D-YAML/issues/63
Imho it's time to test it on project tester:
> Add D-YAML to the Jenkins Autotester

- ansible/ci.yml
- ansible/inventory
- ansible/roles/dub_registry_mirror/files/dub-registry-mirror.service
- ansible/roles/dub_registry_mirror/files/dub-registry.patch
- ansible/roles/dub_registry_mirror/handlers/main.yml
- ansible/roles/dub_registry_mirror/tasks/main.yml
- ansible/roles/haproxy/tasks/main.yml
- pipeline.groovy
Should reduce failures due to network connectivity issues.
> provision dub-registry mirror on code-mirror.dlang.io

- pipeline.groovy
- https://github.com/rejectedsoftware/vibe.d/issues/1844#issuecomment-315881639
> problem with vibe-d tests was resolved

- ansible/roles/jenkins_slave/templates/jenkins.service.j2
- to prevent any test from running the server OOM
- The 16GiB limit is hopefully enough for 4 executor slots.
> add memory limit to Jenkins executor

- pipeline.groovy
See also: https://github.com/dlang/dmd/pull/7135
> Preprare Jenkins for the final phase of the ddmd transition

- pipeline.groovy
- reducing slave disk usage
- also workaround dub clean --all-packages bug and remove build libs manually
> clean DPL repos and distribution after stashing compiler

- ansible/roles/jenkins/tasks/main.yml
- due to the small min heap size, the default region size was tiny and
lots of sub-1MiB allocations were treated as humongous.
- also log GC activity for analysis
> increase G1HeapRegionSize to 32MB

- Jenkinsfile
- vars/runPipeline.groovy
- avoids checkout of the whole ci repo
- temporarily added symlink for now to not break other dlang Jenkinsfiles
> use Library to load pipeline.groovy script

- ansible/ci.yml
- vars/runPipeline.groovy
Recently (https://github.com/sociomantic-tsunami/ocean/pull/321) we have enabled CI testing with vanilla upstream DMD compiler for WIP ocean major branch, as 2.077 provided necessary `Throwable.message()`. 
Would appreciate getting it to the list of automatically tested projects ;)
> Start testing Sociomantic ocean in pipeline

- vars/runPipeline.groovy
Removing functions from Phobos can easily break undeaD. We need to prevent that if we want to continue to able to aggressively deprecate functionality that's not up to standards of Phobos.
> Add 'dlang/undeaD' to the pipeline

- vars/runPipeline.groovy
Vibe.d 0.8.3 won't include `std.experimental.allocator` anymore.
See also: https://github.com/vibe-d/vibe.d/pull/1983
Needed for https://github.com/dlang/phobos/pull/5921
> Bump vibe-d to 0.8.3-alpha.1

- vars/runPipeline.groovy
This test is permanently failing, see e.g.:
https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-5948/2/pipeline
```
Running ./tests 
core.exception.AssertError@source/app.d(58): Test has hung.
----------------
??:? _d_assert_msg [0x610b6a]
source/app.d:58 pure nothrow @nogc @safe void app.main().__lambda1() [0x555a50]
../../core/vibe/core/core.d:629 void vibe.core.core.makeTaskFuncInfo!(void delegate() @safe).makeTaskFuncInfo(ref void delegate() @safe).callDelegate(vibe.core.core.TaskFuncInfo*) [0x560f27]
../../core/vibe/core/core.d:1269 void vibe.core.core.CoreTask.run() [0x5655a6]
??:? void core.thread.Fiber.run() [0x6468a7]
??:? fiber_entryPoint [0x6465fa]
??:? [0xffffffff]
```
@s-ludwig's idea from #vibe-d-ci on Slack:
> Could it be that the server simply …
> [Vibe-d] Disable hanging test 1726 temporarily

- vars/runPipeline.groovy
When a PR is made directly from an upstream branch or to a different
branch than `master` or `stable`, the respective branch at the other two
repositories might not exist. So let's better check beforehand and
softly fallback to `master` otherwise. The same procedure is e.g. used
for CircleCi.
Note: I'm doing this more or less blind :/
> Use master as fallback for non-existent branches

- vars/runPipeline.groovy
This is preventing some PRs from being merged.
> temporarily remove unit-threaded until failure can be investigated

- vars/runPipeline.groovy
The patch applied in https://github.com/sociomantic-tsunami/ocean/pull/427
doesn't seem to appear in Ocean `v4.0.0-alpha.4` anymore.
Currently it fails:
https://github.com/dlang/dmd/pull/7617
However, Jenkins did pass on
https://github.com/dlang/dmd/pull/7553 and e.g. on
https://github.com/dlang/phobos/pull/6002
> Temporarily patch Ocean to workaround missing out contract patch

- vars/runPipeline.groovy
Now includes requires fix from v3.5.11
> Switch to testing ocean v4.0.0-alpha.5

- vars/runPipeline.groovy
Reverts dlang/ci#121 - `zmq` has been tagged with `1.1.1`
https://github.com/kyllingstad/zmqd/pull/21#issuecomment-357498432
> Revert "Clone zmq form master due to #120"

- vars/runPipeline.groovy
Failing e.g.
- https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdruntime/detail/PR-2048/3/pipeline/193
- https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdub/detail/PR-1339/13/pipeline
- https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-6065/1/pipeline
> Temporarily disable diet-ng

- vars/runPipeline.groovy
- using https://github.com/vibe-d/vibe.d/pull/2016
> parallelize vibe.d tests

- ansible/gce.yml
To accomodate the plenty of space that parallel vibe-d tests require.
> increase disk sizes to 30GiB

- vars/runPipeline.groovy
- rather than for overall delay
- the many slow test-suites immediately clog all executors on a single PR
- mainly to prevent booting an on-demand instance just to quickly run
the remaining queued tests
- will slightly increase overall latency a bit, as slow tests are only
started after all fast tests are done
> optimize test order for minimal queue length

- ansible/inventories/static
- instead of matching dynamic datacenter group
> add GCE/Pbricks slaves to servers group for common config (e.g. zram)

- vars/runPipeline.groovy
Reverts dlang/ci#145
Until it manages to use the pre-installed libclang-4.0-dev, see https://github.com/dlang/ci/pull/145#issuecomment-361104294.
> Revert "Add DStep to the tested projects"

- vars/runPipeline.groovy
I just realized we don't run the testsuite of `dlang/tools`.
> Add dlang/tools to the tested projects

- vars/runPipeline.groovy
```
Testing AENetwork
- getFile
object.Exception@sys/net/ae.d(33): Time-out
----------------
sys/net/ae.d:33 pure @safe void ae.sys.net.ae.AENetwork.getData(immutable(char)[]).__lambda3(immutable(char)[]) [0x8f643b]
net/http/client.d:379 void ae.net.http.client.httpRequest(ae.net.http.common.HttpRequest, void delegate(ae.sys.data.Data), void delegate(immutable(char)[]), int).responseHandler(ae.net.http.common.HttpResponse, immutable(char)[]) [0x887377]
net/http/client.d:201 void ae.net.http.client.HttpClient.processResponse(immutable(char)[]) [0x886b16]
net/http/client.d:210 void ae.net.http.client.HttpClient.onDisconnect(immutable(char)[], ae.net.asockets.DisconnectType) [0x886b6a]
net/asockets.d:1398 void ae.net.asockets.ConnectionAdapter.onDisconnect(immutable(char)[], …
```
> Remove network tests for ae due to frequent timeouts

- vars/runPipeline.groovy
- so that projects can selectively disable certain less reliable tests
> add env variable as deterministic test hint

- vars/runPipeline.groovy
> Add automem to the list of tested projects

- vars/runPipeline.groovy
> Add requests library to the Projects Tester

- vars/runPipeline.groovy
It's currently broken again with `master`:
```
/home/seb/dlang/dmd/generated/linux/release/64/../../../../../phobos/std/algorithm/iteration.d-mixin-2498(2510,17): Error: cannot modify struct this._current Result with immutable members
source/dlangbot/bugzilla.d(43,9): Error: template instance std.algorithm.iteration.joiner!(MapResult!(__lambda2, Json[])) error instantiating
```
I will dig a bit into this issue, but once it's fixed, we should really add the dlang-bot to the projects tested.
> Add dlang-bot to the tested projects

- vars/runPipeline.groovy
This should prevent regressions like https://issues.dlang.org/show_bug.cgi?id=18430
CC @9il
FYI: the latest stable git tag is checked out
(this probably first requires the regression fix)
> Add mir projects to the Project Tester

- vars/runPipeline.groovy
One of Symmetry Investments sponsored projects. Tests are very quick to run so shouldn't cause much extra load.
> Add kaleidicassociates/excel-d to tested projects

- vars/runPipeline.groovy
Ocean seems to be constantly failing on all PRs at the moment.
Example: https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-6513/2/pipeline
As I'm leaving for a week of vaction in two hours, I am temporarily deactivating it.
Any help to figuring out the cause of the failure and re-enabling is very welcome.
CC @mihails-strasuns-sociomantic @mathias-lang-sociomantic @nemanja-boric-sociomantic
@leandro-lucarella-sociomantic @david-eckardt-sociomantic
> Temporarily disable the Ocean library.

- vars/runPipeline.groovy
See https://github.com/dlang/dmd/pull/8241
Last PR was merged in 2017: https://github.com/msgpack/msgpack-d/pulls?q=is%3Apr+is%3Aclosed and the project seems generally unmaintained, e.g. https://github.com/msgpack/msgpack-d/pull/100
If there's active interest in the project, this PR can always easily be reverted.
> Remove msgpack-d due to inactivity

- vars/runPipeline.groovy
CC @Shachar, @tomerfiliba, @JohanEngelen I noticed that 2.081 broke building Mecca and that's very unfortunate.
With enabling it at the project tester we can guarantee that all future PRs need to pass Mecca's testsuite.
The latest git tag is checked out and by default the testing instructions from the `.travis.yml` are performed.
> Add Mecca to the Project Tester

- vars/runPipeline.groovy
Sönke retagged 1.4.1 and I think there's still an invalid copy of it laying around.
See also: https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fci/detail/PR-225/52/pipeline
> Purge all dub packages

- README.md
- buildkite.sh
- buildkite/build_distribution.sh
- buildkite/build_project.sh
- buildkite/setup_linux.sh
- buildkite/travis_get_script
Preview: https://buildkite.com/d-lang/dmd-test/builds
TODO:
```bash
if [ [ "$BUILDKITE_PULL_REQUEST" == "false" ] && [ "$BUILDKITE_PULL_REQUEST_REPO" != "git://github.com/dlang/ci.git" ] ] ; then
wget https://github.com/dlang/ci/raw/master/buildkite.sh
fi
bash buildkite.sh | buildkite-agent pipeline upload
```
```bash
sudo apt-get update
sudo apt-get install -y apt-transport-https sudo
sudo sh -c 'echo deb https://apt.buildkite.com/buildkite-agent stable main > /etc/apt/sources.list.d/buildkite-agent.list'
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 32A37959C2FA5C3C99EFBC32A79206696452D198
sudo apt-get update && sudo apt-get install -y buildkite-agent
sudo systemctl enable buildkite-agent@1 && systemctl start buildkite-agent@1
sudo systemctl enable …
```
> Add buildkite config script

- buildkite/build_distribution.sh
- buildkite/build_project.sh
Buildkite interprets `+++` as new group that should be opened.
This simply sets `PS4` to a different symbol, s.t. no groups are
accidentally opened.
See also: https://buildkite.com/docs/builds/managing-log-output#collapsing-output
> Avoid accidentally opening new log sections with bash's tracing output

- buildkite/build_distribution.sh
Should be a bit faster and avoid any potential conflicts by having a clean root folder.
> Use mv instead of cp when cloning the repositories

- buildkite/build_distribution.sh
Just to be safe and in case it's needed in the future.
> Don't move the buildkite folder when creating the distribution

- ansible/ci.yml
Apparentely lubeck needs this since the recent 0.1: https://buildkite.com/dlang/dmd/builds/202#14a669e8-1d9d-4e32-ac49-79c6d5e71b17
> Add libopenblas-dev to the buildkite agents

- buildkite.sh
Looking at the logs it seems that unit-threaded doesn't build anymore.
CC @atilaneves
e.g. https://buildkite.com/dlang/ci/builds/173#cfaf1389-9f04-415f-8d70-ed5196491cdb
```
Linking...
TERM environment variable not set.
```
> Temporarily disable unit-threaded

- buildkite/build_distribution.sh
This should checkout the `stable` branch when it is actually required.
> Fix stable PRs for Buildkite

- buildkite.sh
- buildkite/build_distribution.sh
- buildkite/clone_repositories.sh
- buildkite/test_coverage.sh
A first step at fixing https://github.com/dlang/ci/issues/19.
The idea is to unite a few CIs and CircleCi is one of easier.
However, we probably want to define the exact Coverage steps as a `coverage` target in the individual repositories (or maybe even as a `codecov` target as the submit step is also different.) -> `codecov.sh` script
> Run CodeCov on Buildkite

- buildkite.sh
As it's becoming more hyped on the forums and we want to avoid breaking high-impact tools with new DMD releases.
CC @LaurentTreguier - there should be nothing required on your side (this is just an FYI).
The project tester will automatically test the latest (stable) released version and use the same testing scripts as you have defined in your `.travis.yml`.
The Buildkite account is still private, but you can use the dummy account (dummy@dlang.io, "dlangrocks") to browse the logs.)
> Add dls to the project tester

- buildkite.sh
As they now use the built distribution archive, they need to run `merge_head` separately.
> Merge with the upstream head for style + coverage targets

- buildkite.sh
Until the breakage has been resolved, e.g.
https://buildkite.com/dlang/phobos/builds/180#3399564a-7cc7-4850-955c-101f35d33b6b
FYI: @jmdavis
This looks like the skipOver PR https://github.com/dlang/phobos/pull/6143 introduced a breakage in your dxml library.
I will for now disable dxml and then immediately open the revert, s.t. we can enable it later (once the regression has been fixed.)
> Temporarily disable dxml

- buildkite/clone_repositories.sh
The failure was due to clone_repositories trying to move the existing files into the BUILDKITE_REPO folder.
This, however, doesn't work for the dlang/phobos target as it doesn't checkout phobos as in `build_project` it's unknown whether the master or stable branch or another one should be used.
> Fix Phobos target

- buildkite/clone_repositories.sh
We really need a better way to simulate dmd/druntime/phobos builds for the ci repository.
Maybe we can just add them as separate pipelines to the CI repo? But I guess checking out the respective PR and the branch logic might not work then...
> Fix Phobos (v2)

- buildkite.sh
Now that we have a lot more agents, this performance hack doesn't make sense anymore.
> Remove forcing slowly-running to run on 'low' memory machines only

- buildkite.sh
- buildkite/build_project.sh
@kinke noted when updating ldc that the issue was with a self-compiled ldc crashing because of some C++ interfacing issues, so I tried to recreate that as much as possible. This will make this test run more than twice as long, but I'm not sure the previous version would have caught C++ interfacing issues.
> Make LDC master build itself, using ninja

- ansible/ci.yml
> LDC master now requires LLVM 3.9

- buildkite.sh
- buildkite/load_distribution.sh
CC @gecko0307 are you okay with having a bit more testing of your projects?
For this to work, I think you need to update dlib, s.t. it doesn't use the removed `std.c` modules.
Then in the future, such hard breakage can't happen again.
> Add dagon to the Project Tester

- buildkite/build_project.sh
- buildkite/clone_repositories.sh
- buildkite/origin_target_branch.sh
The problem was that when Phobos (or dub or tools for that matter) is tested as a project, it used the same logic as all the other to-be-tested projects (i.e. fetching and checking out the latest tag).
With this PR the core repositories will use the same logic as its existing in the build_distribution step:
- merge the PR head into the target branch (if it's the same repo)
- otherwise check if the branch from the repo that triggered the PR exists in the to-be-tested repo (master and stable always exist)
- otherwise checkout master
> Fix #308 - wrong version of Phobos is checked out during testing it as a project

- ansible/ci.yml
- ansible/roles/buildkite_agent/defaults/main.yml
Higher priority agents are assigned work first.
See also: https://buildkite.com/docs/agent/v3/prioritization
> Increase the buildkite-agents priority

- buildkite/build_project.sh
https://github.com/vibe-d/eventcore/pull/86 broke these jobs (see e.g. https://buildkite.com/dlang/ci/builds/447#20a4e124-5d52-4281-8ca5-4268b21af56b)
This temporarily disables the builds and I will revert this immediately afterwards, s.t. we can reenable it once fixed.
> Disable failing vibe.d (with vibe-core) jobs until eventcore is fixed

- buildkite.sh
Moved the default commands into a common variable, s.t. for future steps this isn't forgotten.
> Don't build Buildkite on dmd-cxx

- buildkite.sh
- for vibe.d examples
See https://buildkite.com/dlang/dub/builds/229#6f781f60-ea4c-451b-b5d5-56318978ebb3 for a failure.
> slightly increase job timeout

- ansible/inventories/static
> reduce number of buildkite agents on ci server

- buildkite/clone_repositories.sh
At the moment the druntime style target is failing because it requires `git ls-tree` to work (see e.g. https://github.com/dlang/druntime/pull/2380).
The reason why `git ls-tree` doesn't work is that the `.git` simply doesn't exist.
Long explanation:
When we try to create the actual D core repository structure in the Buildkite repo, we can't go up in the file hierarchy. Thus, we go "down" by moving the content of the currently checkout out PR in its respective subfolder and clone the respective target branch (master, stable, etc.) from the other required core repositories.
See `clone_repositories` for details.
For now, `.git` wasn't moved to keep at least the main repository cached, but a workaround here is to copy the `.git` folder over.
A better long-term solution would be to use custom …
> Copy over .git to current repository

- buildkite.sh
After https://github.com/d-language-server/dls/pull/17, dls now doesn't have a fixed dub version in `dub.selections.json` anymore, but I'm not entirely satisfied with simply removing it, for three reasons:
- it goes against reproducible builds, which is something I prefer having (in case I need to find out about a regression somewhere or anything)
- when launching a simple build, dub rewrites `dub.selections.json` with all the required dependencies, adding the `dub` line again and automatically dirtying the file in the process
- I'm an airhead, and I might just re-add the line in the repo by accident when upgrading other dependencies
The 2 commits in this PR:
- rename the repository (as I moved it and other related repos under an organization)
- add an entry in `build_project.sh` to erase …
> Rename LaurentTreguier/dls -> d-language-server/dls

- buildkite/clone_repositories.sh
Yet another attempt at fixing Buildkite.
> fix(clone_repos): only moves files of the repository from which the PR originated

- buildkite.sh
There's no real point in testing Buildkite when run e.g. at dmd.
> fix(buildkite): only self-test for PRs to dlang/ci

- buildkite/build_project.sh
This needs to be in master for it to take effect, but at the moment I don't know why dlang/dub is failing at dlang/dub (or dlang/druntime at dlang/druntime).
> debug: list the entire directory layout when testing an already checked out core project

- buildkite/build_project.sh
- buildkite/clone_repositories.sh
If a project triggers a PR (e.g. dlang/phobos), then it shouldn't be recloned
if dlang/phobos needs to be tested. This logic is already in `build_project`
and `clone_repositories`.
At the moment, builds are done in the subfolder `build`, but the
`clone_repositories` script assumes that we're at the git root folder.
This should fix many of the remaining Buildkite failures (maybe even #355).
> Fix clone_repositories if a project repository triggered the build

- buildkite.sh
This should help to avoid spurious failures when there are left-overs from previous builds.
(We already use it for almost all targets except for e.g. "style".)
> Force-clean git repository before building

- buildkite.sh
The on-demand provided Buildkite agents seem to be really slow.
> Increase timeout to 60 minutes

- buildkite/build_distribution.sh
- also see https://github.com/dlang/dub/pull/1589 and
https://github.com/dlang/dub/pull/1624
- reduces test time for vibe-d's examples by ~50%
> enable dub's experimental build cache improvements

- buildkite/build_release_pipeline.yml
Random failures also seem to happen here, the retry logic helped us quite a lot for the CI pipelines, so I think it could be benefitial here too.
See e.g. https://buildkite.com/dlang/build-release/builds/112#25005182-8ce8-46f7-a2c6-4ebd94b2c960
> Retry nightly builds up to 3 times

- buildkite.sh
Reverts dlang/ci#376
So that it doesn't get lost, but lubeck has a bad track history now and I don't feel too inclined to have a project here which releases things with a broken CI on the project :/
> Revert "Disable Lubeck as it fails with dependency errors"

- buildkite/build_project.sh
Starting from v5.0.0, ocean dropped D1 support and is D2 only.
CC @mihails-strasuns @leandro-lucarella-sociomantic
> ocean: Do not run d2conv

- buildkite/build_project.sh
It is now handled in https://github.com/CyberShadow/ae/releases/tag/v0.0.2389.
Needed to unbreak ae in the BuildKite project tester.
> buildkite/build_project.sh: Remove ae.sys.net.test hack

- buildkite.sh
Buildkite is broken pending https://github.com/weka-io/mecca/pull/23
As soon as the aforementioned PR is merged we can revert this.
> Disable Mecca pending PR merge

- buildkite.sh
Reverts dlang/ci#395
Unfortunately the fix is not enough, apparently... And terrible to test.
Personally I'm fed up with fixing linking errors triggered by access to private symbols.
> Disable Mecca once again

- buildkite/clone_repositories.sh
Reverts dlang/ci#352
Logs is as follows currently:
```
~> repositories=(dmd druntime phobos tools dub)
--
  | ~> '[' dlang/phobos == dlang/ci ']'
  | ~> for dir in '"${repositories[@]}"'
  | ~> '[' dmd == dmd ']'
  | ~> '[' dlang/phobos == x ']'
  | ~~> basename dlang/phobos
  | ~> '[' phobos == dmd ']'
  | ~> for dir in '"${repositories[@]}"'
...
  | ~> '[' dmd == dub ']'
  | ~> for dir in '"${repositories[@]}"'
  | ~> '[' '!' -d dmd ']'
  | ~> repo=https://github.com/dlang/dmd
  | ~~> /var/lib/buildkite-agent/builds/ci-agent-3336cc36-2797-42b6-ba5b-167d05f41167-1/dlang/dmd/build/buildkite/origin_target_branch.sh https://github.com/dlang/dmd
  | ~> branch=master
  | ~> echo 'target_branch: master'
  | target_branch: master
  | ~> git clone -b master --depth 1 https://github.com/dlang/dmd …
```
> Revert "fix(clone_repos): only moves files of the repository from which the PR originated"

- buildkite.sh
- use only a single retry to workaround excessive time spent on actual failures
> reduce excessive retries

- buildkite/build_project.sh
Workaround unnecessary since https://github.com/dlang/dub/pull/1854
The exact call to `travis-ci.sh` blocks https://github.com/dlang/dub/pull/1853
> Dub: Remove workaround, use Travis' script

- buildkite/build_project.sh
Since the script is not versioned, those kinds of errors are quite common.
Using `git merge-base` seems like the most resilient option, as it won't break in the future.
> Fix dub testing on stable

- buildkite.sh
```
Since the new release, it requires a zmq >= 4.3 but the machines have 4.1.4.
```
A temporary measure to make Buildkite green again...
@wilzbach : I grepped for `zmq` but I only saw a reference to version 3 (?) in ansible. Any chance you could take a look at this ?
CC @kyllingstad (sorry, didn't foresee that one).
> Disable kyllingstad/zmqd

- buildkite.sh
- buildkite/build_project.sh
Those backends were deprecated, and are gone in master, so we're essentially building the same backend multiple times. Also removed a few outdated comment and re-activated a test that is fixed.
CC @s-ludwig
BTW there are a few `vibe-core` tests in vibe-d, should they be moved over to the new repository ?
> Vibe.d: Clean up and remove non-Vibe-core backend

- buildkite/build_project.sh
As a band-aid for the CI regression (due to LDC master now requiring LLVM 6+). Note that the next beta is scheduled for this evening, so someone should look into raising the installed LLVM version ASAP.
> BuildKite: Don't use LDC *master* (but the latest tag instead)

- ansible/roles/test_deps/tasks/main.yml
LLVM 6.0+ will be required from the next LDC release
(and is already required for LDC master).
> ansible: Bump LLVM to 8.0

- buildkite/build_project.sh
The LLVM 8 libs seem unusable with the used bfd linker; switch to gold.
> Fix LDC regression with new Ansible image

- buildkite.sh
- buildkite/build_project.sh
This is the next step in the process. In order to test autodecode PRs actually work and don't break later, we need to be able to test modules with no autodecode enabled as they are fixed.
See plan in https://github.com/dlang/phobos/pull/7586
> Add autodecode test to buildkite.

- ansible/roles/test_deps/tasks/main.yml
- buildkite/Dockerfile
```
This Dockerfile will allow administrator to quickly and easily deploy an agent.
The dependencies were extracted from ansible/roles/test_deps/tasks/main.yml.
A user can run the agent with:
$ docker build -t buildkite_agent buildkite
$ docker run -e BUILDKITE_AGENT_TOKEN='AGENT-TOKEN-HERE' buildkite_agent
Note that since this image is not intended to be distributed, the usual cleanup isn't done
(and no attempt was made to minimize the dependencies).
```
CC @wilzbach @PetarKirov : I'm running this on my server now so if any issue shows up we'll know soon enough. Might want to give it a few days to see if nothing fails (@wilzbach originally spotted failures because Ocean has a hard dependency on OpenSSL 1.0.0 and Arch only provides 1.1).
> Add a Dockerfile to build an agent

- buildkite/build_distribution.sh
Can be merged after https://github.com/dlang/dmd/pull/11580 is in stable and master.
Not necessary as backwards compatibility should be provided (for now), but gets rid of deprecation messages and allows to remove the posix.mak file one day.
> Use newer bootstrap.sh to build DMD

- buildkite/build_project.sh
> Build of intel-intrinsics needs one additional envvar.

- buildkite/build_project.sh
The configuration 'vibed' was removed from dlang-requests in version
2.0.0, so attempting to build it will always fail.
---
This is currently blocking all new PRs to dmd/druntime/phobos.
> Don't build removed dlang-requests configuration

- buildkite.sh
> Increase the number of retries (1->3)

- buildkite/build_project.sh
- buildkite/clone_repositories.sh
First, the default git clone will output progress message every percent of the way, which is not useful for offline log inspection.
Second, buildkite uses the `---` prefix to group log output. However, that's not nested so calling the cloning script will group things the wrong way. So I added those `echo`s to distinguish cloning from building.
Related: isn't it excessive to output every single command run? I'd understand doing so temporarily for debugging (and even in that case I'd argue well-thought logging would be vastly better), but to leave it on by default seems much.
> Reduce a bit of the soul-crushing log spam created by buildkite

- buildkite/build_project.sh
This prepares Buildkite for https://github.com/dlang/dmd/pull/13593.
> Buildkite: Bump LDC to master, to prepare for upcoming breaking opEquals order change

- buildkite/build_distribution.sh
- buildkite/build_project.sh
- buildkite/clone_repositories.sh
We need to keep pre-merge logic around for build_distribution,
which is not too much logic.
> Allow to build both pre-merge and post-merge druntime

- ansible/gen_release-builder_scaleway_image.yml
- ansible/roles/dub_registry_mirror/tasks/main.yml
- buildkite/build_release.sh
This is now possible now the site now has a new front for its bucket.
> Update downloads.dlang.org links to use https

- buildkite.sh
serialized also indirectly validates Funkwerk's boilerplate, dshould and prettyprint.
All of them are template heavy and well unittested, so it would be useful to have early warning if one of them was broken by a change.
Comment times are based on local runs.
> Add Funkwerk Mobility `serialized` and `mocked`.

- buildkite/Dockerfile
The existing LLVM 14 (Ubuntu 22 default) is too old.
> Dockerfile: Add LLVM 15, the min version required for LDC v1.39

- buildkite.sh
AFAICT https://github.com/symmetryinvestments/lubeck is gone.
→ https://github.com/dlang/phobos/issues/10583
> Replace gone symmetryinvestments/lubeck with kaleidicassociates/lubeck

- buildkite/build_project.sh
See https://github.com/dlang/dub/pull/3064#issuecomment-3140878190
1. It does nothing
2. It causes the run to fail when the tests are renamed/removed
> dlang/dub: Don't try to remove tests that aren't run
