- Jenkinsfile
- ProjectsJenkinsfile
- run parallel around node (to throttle and distribute parallelism across executors)
- directly load ProjectsJenkinsfile
- more project testing
- couple of fixes
> pipeline changes/fixes

- Jenkinsfile
Fixes checkout to use PR branch for tested repo instead of all master
> Support PR testing pipeline

- pipeline.groovy
- similar env to install.sh/Travis-CI
- run .travis.yml script
- put shared libs into distribution
- clean dub build caches
- .dub folder per workspace
> some improvements on project tests

- pipeline.groovy
- also use unified workspace for testing dub projects
- mainly to reuse git clones
> fix #22 - fix unified workspace

- pipeline.groovy
- in order to fix deadlocks when multiple jobs are all waiting for executors
> avoid nesting node blocks, fixes #30

- pipeline.groovy
- fixes issues w/ GH rate limit
- also support non-master branch builds (e.g. stable)
> get base branch from env

- pipeline.groovy
- still being a workaround for the core.thread.Fiber.state change
> update to vibe-d 0.7.31-rc.2

- pipeline.groovy
Equivalent of https://github.com/dlang/dmd/pull/6685
> print toolchain/system info

- pipeline.groovy
This library is used for Digger, DAutoTest and DFeed.
> Add CyberShadow/ae

- Jenkinsfile
Maybe using some intermediate script that loads the real pipeline to keep this out of the dlang repos.
https://github.com/jenkinsci/workflow-remote-loader-plugin
Just use the Jenkinsfile, repo should already get cloned by Jenkins.
> Test updates to CI repo itself

- Jenkinsfile
- No idea how to remove the checkout that's done to load the
Jenkinsfile, guess I might resort to a server cron job.
> cannot deleteDir outside of a node

- pipeline.groovy
- until it's clear why thread joining fails
> allow failure on vibe-d libasync

- pipeline.groovy
- https://github.com/rejectedsoftware/vibe.d/issues/1844
> test vibe 0.7.x to workaround Issue 1844

- pipeline.groovy
> add timelimit to pipeline

- pipeline.groovy
- to help https://github.com/dlang/dmd/pull/6998
> test vibe 0.8.1-beta.1

- ansible/roles/jenkins/tasks/main.yml
- hopefully improving horrible load times a bit
> use concurrent G1GC

- ansible/roles/jenkins_slave/tasks/main.yml
- boot time too long to speed up single PRs
> reduce on-demand slave usage

- vars/runPipeline.groovy
Sadly not all projects use the same setup and respect $DC.
> Add more projects from dlang-community

- ansible/ci.yml
- ansible/gce.yml
- ansible/group_vars/jenkins_gce_slaves
- ansible/inventories/static
- also move instances closer to Jenkins master (FRA)
> add 2nd GCE on-demand instance

- vars/runPipeline.groovy
- fallback has been added to dub itself
> no longer necessary to patch defaultRegistryURL

- vars/runPipeline.groovy
Doing this more or less bindly and relying on Jenkins for feedback.
> Add pegged and ebay-tsv-utils to the projects tested.

- ansible/group_vars/jenkins_gce_slaves
- ansible/group_vars/jenkins_pbricks_slaves
- ansible/roles/jenkins_slave/tasks/main.yml
- so a few queued jobs do not boot all servers at once
> staggered launching of on-demands slaves

- vars/runPipeline.groovy
- catch ClosedChannelException as proxy to mean preempted slave
> implement retry when executor gets preempted

- vars/runPipeline.groovy
I will look into submitting a PR to zmq soon.
> Clone zmq due to #120

- vars/runPipeline.groovy
It regularily broke in the past..
Broken build: https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fci/detail/PR-119/1/pipeline/200
> Add dlang-tour to the tested projects

- vars/runPipeline.groovy
> Revert "Temporarily disable diet-ng"

- ansible/roles/jenkins_slave/tasks/main.yml
- workaround for dlang/dub#631
> regularly clean old packages from dub's build/pkg cache

- vars/runPipeline.groovy
- so one doesn't have to dig those out of the raw log
> echo node name and workspace

- vars/runPipeline.groovy
See also: https://github.com/BlackEdder/ggplotd/pull/45
> Temporarily disable ggplotd

- vars/runPipeline.groovy
See also: https://github.com/vibe-d/vibe.d/issues/2066
> Remove flaky Vibe.d test: tests/vibe.core.net.1452

- vars/runPipeline.groovy
See also: https://github.com/vibe-d/vibe.d/issues/2068
> Disable flaky vibe-d test: tests/vibe.core.net.1376

- ansible/roles/haproxy/tasks/main.yml
Also see #110 and 05431a9ec0d51fe1aeb5b9f86732d8f95ad83ae6
> update to HAProxy 1.8.4 and switch on HTTP/2

- vars/runPipeline.groovy
- Motivated by 2 or 3 regs per year due to the diversity of style present in this lib.
- runs in 25 secs on SemaphoreCI, might be slightly slower here.
> add "iz", close #177

- vars/runPipeline.groovy
See also: https://github.com/vibe-d/vibe.d/issues/2078
> Disable spurious vibe.d/tests/redis

- vars/runPipeline.groovy
See also: https://github.com/vibe-d/vibe.d/pull/2081
> Bump vibe.d to v0.8.3-alpha.5

- vars/runPipeline.groovy
> Bump vibe.d to 0.8.3-beta.1

- vars/runPipeline.groovy
Trying to to get the root cause of https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-6391/2/pipeline/
> Build dub in gdb to get the stacktrace

- ansible/roles/dub_registry_mirror/defaults/main.yml
- to fix syncing with code.dlang.org
> update dub-registry on code-mirror.dlang.io

- vars/runPipeline.groovy
> Revert "Temporarily disable DCD"

- vars/runPipeline.groovy
> revert #190 workarounds - reenable projects

- vars/runPipeline.groovy
See also: https://github.com/vibe-d/vibe.d/issues/2157
> Disable segfaulting libevent test

- vars/runPipeline.groovy
Reverts dlang/ci#208
(s.t. reverting this doesn't get forgotten)
> Revert "Temporarily disable the Ocean library."

- vars/runPipeline.groovy
The issues with the dub registry have been mostly resolved. Time to enable these projects again.
> Re-enable disabled projects

- vars/runPipeline.groovy
CC @mbierlee - I presume you are ok with this?
> Add poodinis to the Project Tester

- vars/runPipeline.groovy
CC @p0nce - ping me once it's passing on 2.081 and then we can get this merged here.
> Add intel-intrinsics package

- vars/runPipeline.groovy
It has been moved a long time ago.
> Set containers repo to dlang-community

- buildkite.sh
- buildkite/build_distribution.sh
- buildkite/build_project.sh
This makes the build a bit slower, but avoids random failures.
> Only run dub & dlang-bot on high-memory agents

- buildkite/build_distribution.sh
- buildkite/build_project.sh
https://buildkite.com/docs/builds/managing-log-output#collapsing-output
> Add separate sub-commands for buildkite

- buildkite/build_project.sh
- vars/runPipeline.groovy
> Rename tsv-utils-dlang -> tsv-utils

- buildkite/build_project.sh
- vars/runPipeline.groovy
> Use latest Vibe.d on the project tester

- buildkite.sh
- vars/runPipeline.groovy
Looks like I only did the rename partially.
See also: https://github.com/dlang/ci/pull/244
> Update tsv-utils-dlang -> tsv-utils

- ansible/README.md
- ansible/ci.yml
- ansible/files/default_authorized_keys
- ansible/roles/lxd_host/tasks/main.yml
- ansible/roles/users/tasks/create-users.yml
- ansible/roles/users/tasks/main.yml
- ansible/roles/users/vars/main.yml
- authorize admins for hosts and containers
> add users role

- README.md
- buildkite.sh
- buildkite/build_project.sh
It somehow got broken.
This also adds advice on how to reproduce a failure locally.
> Re-enable the tools repo for Buildkite

- buildkite.sh
https://buildkite.com/docs/pipelines/command-step#automatic-retry-attributes
> Automatically retry failing builds

- buildkite/build_distribution.sh
Otherwise already cloned repositories will be moved too.
> Move the current project first

- ansible/ci.yml
- buildkite.sh
- buildkite/build_project.sh
Not sure whether this works directly on Jenkins or requires further intervention.
Depending on the time it takes to run the testsuite, maybe it's enough to just run the fail_compilation / compilable tests.
> Add LDC to the project tester

- buildkite.sh
In theory that should be all that it takes. I might need to adjust the position based on how long the testsuite takes to run.
CC @jmdavis
> Add dxml to the project tester

- buildkite.sh
- buildkite/build_project.sh
- buildkite/load_distribution.sh
`dub` is required for the style target at Phobos.
> Load distribution for the style target too

- buildkite.sh
- buildkite/build_project.sh
Small library, but does use a few interesting D features.
> Add optional to the project tester

- buildkite.sh
- buildkite/build_project.sh
A small lib, but it uses a few interesting D features.
> Add sumtype to the project tester

- buildkite.sh
Reverts dlang/ci#285
See e.g. https://buildkite.com/dlang/phobos/builds/180#3399564a-7cc7-4850-955c-101f35d33b6b
It looks like the skipOver PR (dlang/phobos#6143) introduced this regression.
CC @jmdavis
> Revert "Temporarily disable dxml"

- buildkite/build_project.sh
> Group a few DUB projects with equal build commands

- buildkite.sh
See e.g. https://github.com/dlang/ci/pull/296#issuecomment-415458109
> Disable LDC until the recent failure has been resolved

- ansible/ci.yml
- buildkite.sh
- requires llvm-dev (not just llvm)
> fix ldc testing

- ansible/ci.yml
- ansible/group_vars/jenkins_gce_slaves
- ansible/inventories/static
- ansible/roles/jenkins/defaults/main.yml
- ansible/vagrant_inventory
- keep jenkins running for now to serve historical PR results
> remove jenkins runners

- buildkite/build_project.sh
See also: https://github.com/dlang/dub/pull/1579
> Fix Dub's failure due to GitHub API bug

- buildkite.sh
See also: https://github.com/dlang/ci/pull/328
> Only run dlang/phobos on high memory machines

- buildkite/build_project.sh
was missing a call to use_travis_test_script but the workaround was no longer needed anyhow
> fix ddox test

- ansible/files/Vagrantfile
- ansible/gen_release-builder_scaleway_image.yml
- slightly increase boot timeout
> default configuration for vagrant/virtualbox

- buildkite.sh
- buildkite/build_project.sh
See also: https://github.com/dlang/druntime/pull/2376#issuecomment-442453032
> Fix merging head logic and checkout a respective PR for the dlang projects

- buildkite.sh
- buildkite/build_project.sh
This repo has no tags so `git describe` gives `fatal: No names found, cannot describe anything.`
> [dlang/ci] use git describe --always

- buildkite/build_project.sh
An attempt at fixing https://github.com/dlang/ci/issues/360
> DLS: Experiment with removing editorconfig files

- buildkite/build_release_pipeline.yml
Reverts dlang/ci#371
See https://github.com/dlang/ci/pull/371#issuecomment-450501473
> Revert "Retry nightly builds up to 3 times"

- buildkite.sh
> Disable Buildkite for dmd-cxx

- buildkite.sh
https://github.com/kaleidicassociates/lubeck/issues/21
> Disable Lubeck as it fails with dependency errors

- buildkite.sh
- buildkite/build_project.sh
Merge ASAP please, the old links are not redirected.
> update links for the project "iz"

- buildkite.sh
It's the last project to finish these days, maybe at some point its tests became slower than they used to be.
> run dlang-bot tests earlier

- buildkite.sh
- buildkite/build_project.sh
Naive attempt to see if there is anything unexpected.
> Add sociomantic-tsunami/turtle project

- buildkite.sh
> Revert "Disable libmir/mir temporarily"

- buildkite.sh
Laurent T. has evoked himself this possible solution [here](https://github.com/d-language-server/dls/issues/45#issuecomment-493679504) and today after checking what's new in DMD PR queue I see again the problem.
> deactivate dls due to its random failures

- buildkite.sh
- buildkite/build_project.sh
This is a naive attempt to add swarm to the dlang ci, now that it is a D2 project .
> Add sociomantic-tsunami/swarm project

- buildkite.sh
[This commit](https://github.com/d-gamedev-team/gfm/commit/bd0dcd09497a2c1f421b2aebef40430ca6bdeeea#commitcomment-33877820) broke their own CI I believe. ping @d-gamedev-team, if you can fix from your side instead.
> deactivate GFM

- buildkite.sh
Reverts dlang/ci#393
CC @Geod24
> Revert "Disable Mecca pending PR merge"

- buildkite.sh
Code.dlang.org seems to be having massive issues with gitlab again.
> Temporarily remove optional

- buildkite.sh
> Revert "Temporarily remove optional"

- buildkite.sh
- buildkite/build_project.sh
The user apparently deleted their Github account.
> Remove Basile-z/iz from the list of packages

- buildkite/build_project.sh
See also: https://github.com/vibe-d/vibe-core/issues/184
> Disable vibe/vibe-core: tests/vibe.core.process.d

- buildkite.sh
There used to be a problem with fetching gitlab packages, which has been fixed I believe?
> Re-enable optional

- buildkite/build_project.sh
Can be observed e.g. here: https://buildkite.com/dlang/dmd/builds/11209#3fdfa23a-5c89-49a6-b701-b68626778731
See also: https://github.com/vibe-d/vibe-core/issues/190
> Vibe-core: disable flaky test 1452

- buildkite.sh
- buildkite/build_project.sh
Just got the project building with the latest dmd. I want to add it here so it doesn't get broken again.
> add Martin Nowak's std.io project

- buildkite.sh
> Disable {libevent,vibe-core}-tests

- buildkite.sh
Reverts dlang/ci#412
v0.8.50 has been released.
> Revert "Disable {libevent,vibe-core}-tests"

- buildkite.sh
Another case of meson breaking the build.
> Temporarily disable taggedalgebraic

- buildkite.sh
Reverts dlang/ci#415
See https://github.com/s-ludwig/taggedalgebraic/pull/54
> Revert "Temporarily disable taggedalgebraic"

- buildkite.sh
It is currently broken and holding back development.
CC @Herringway
> Disable D-YAML

- buildkite.sh
> Revert "Disable D-YAML"

- buildkite/build_project.sh
Reverts dlang/ci#425. Can be used to test whether the test works again.
See also: https://github.com/dlang-community/libdparse/issues/431
> Revert "Temporarily use fixed version for libdparse ..."

- buildkite/build_project.sh
Fixes https://github.com/dlang/ci/issues/430
> set -eu for Travis

- buildkite.sh
- buildkite/build_project.sh
The travis-ci script was removed so we need to make it explicit now.
> Add build configuration for dlang-bot

- buildkite/build_project.sh
> Add custom build script for DWT

- buildkite.sh
Until the sqlite3 dependency can be propagated.
> Temporarily disabled dlang-bot

- buildkite/build_project.sh
https://github.com/vibe-d/vibe.d/pull/2611#issuecomment-931362792
> Fix CI by changing vibe.d CI script name

- buildkite/build_project.sh
Keep as draft until vibe-core 1.22.0 is released.
ref: https://github.com/vibe-d/vibe-core/pull/298
> Rename CI script in vibe-core

- buildkite/build_project.sh
This, along with a couple other changes, should (finally) unblock you @dkorpel .
> Buildkite: Use HEAD for sociomantic-tsunami projects

- buildkite/build_project.sh
See https://github.com/vibe-d/vibe.d/issues/2647
> Remove failing vibe-d tls tests

- buildkite.sh
- buildkite/build_distribution.sh
- buildkite/build_project.sh
- buildkite/clone_repositories.sh
Fixes build script paths to work with new merged dmd-druntime repository
See https://github.com/dlang/projects/issues/92
> [project] Merge druntime into the dmd repository

- buildkite/build_distribution.sh
> Adjust druntime copy command for dmd/druntime merge

- buildkite/build_project.sh
> Ping LDC to v1.29.0 to avoid dependency on LLVM >= 9

- buildkite.sh
Latest release broke the CI.
Issue here: https://github.com/AuburnSounds/intel-intrinsics/issues/99
CC @p0nce
> Disable intel-intrinsics

- buildkite.sh
> Revert "Disable intel-intrinsics"

- buildkite.sh
- buildkite/Dockerfile
I'm still experimenting to try to make it work.
I *think* that I have a much more recent version of the agent, which leads to basic stuff not working.
> Improve and update Dockerfile & buildkite script

- buildkite.sh
- buildkite/build_project.sh
Trying to get this to a modern state...
> Improve pipelines by adding documentation and reducing dep on Travis-ci script

- buildkite/Dockerfile
It was not up-to-date for Ubuntu 22.04LTS, which is the Ubuntu version I've got locally by using https://github.com/dlang/ci/blob/master/buildkite/Dockerfile#L24
> Dockerfile: Update dependencies

- buildkite/travis_get_script
Currently, the CI is not happy: https://buildkite.com/dlang/ci/builds?branch=alexandrumc%3Aadd_sym_deps
> travis_get_script: Use python3

- buildkite.sh
Two of the projects that we regularly use internally.
> Add symmetryinvestments' ldapauth project

- buildkite/build_project.sh
Needs: https://github.com/sociomantic-tsunami/ocean/pull/879
> Build sociomantic-tsunami/ocean with OPENSSL_v3

- buildkite/Dockerfile
Needed by https://github.com/dlang/ci/pull/484
> Dockerfile: Install clang

- buildkite.sh
See discussion here: https://github.com/dlang/phobos/pull/10593
> Remove tsv-utils from buildkite
